# Generated by Django 5.2.17 on 2026-08-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('body_md', models.TextField(blank=True)),
                ('published_at', models.DateField()),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('domain', models.CharField(choices=[('streaming', 'Streaming'), ('batch', 'Batch'), ('ai_ml', 'AI / ML'), ('infra', 'Infrastructure')], default='streaming', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('live', 'In production'), ('archived', 'Archived'), ('wip', 'In progress')], default='live', max_length=20)),
                ('summary', models.CharField(help_text='One or two lines. Used on the card / row in the project list.', max_length=280)),
                ('standfirst', models.TextField(blank=True, help_text='The larger paragraph under the title on the detail page.')),
                ('body_md', models.TextField(blank=True, help_text='The case study, in markdown. Headings become the page contents.')),
                ('role', models.CharField(blank=True, max_length=120)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('team', models.CharField(blank=True, max_length=160)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('cover_alt', models.CharField(blank=True, max_length=200)),
                ('headline_metric_label', models.CharField(blank=True, help_text='e.g. p99 freshness', max_length=60)),
                ('headline_metric_value', models.CharField(blank=True, help_text='e.g. 42s', max_length=40)),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower sorts first within a year.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. Data & AI Engineer', max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('hero_quote', models.TextField(help_text='The one line in the hero.')),
                ('hero_quote_attribution', models.CharField(blank=True, max_length=160)),
                ('intro', models.TextField(blank=True, help_text='Short role line under the name.')),
                ('bio_md', models.TextField(blank=True, help_text='Markdown. Shown in About.')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('links', models.JSONField(blank=True, default=dict, help_text='e.g. {"GitHub": "https://…", "LinkedIn": "https://…"}')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site profile',
                'verbose_name_plural': 'site profile',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('tech', 'Technology'), ('concept', 'Concept'), ('cloud', 'Cloud')], default='tech', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Warehouse spend', max_length=60)),
                ('value', models.CharField(help_text='e.g. −38%', max_length=40)),
                ('placement', models.CharField(choices=[('facts', 'Fact bar (under the title)'), ('impact', 'Impact block (in the body)')], default='impact', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio.project')),
            ],
            options={
                'ordering': ['placement', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('diagram', 'Diagram')], default='image', max_length=10)),
                ('ratio', models.CharField(choices=[('21x9', '21:9'), ('16x9', '16:9'), ('4x3', '4:3'), ('4x5', '4:5'), ('1x1', '1:1')], default='16x9', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/assets/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/video/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='projects/posters/')),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('alt', models.CharField(blank=True, max_length=240)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tag'),
        ),
    ]
