# Generated by Django 5.2.17 on 2026-08-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='The language these fields are written in. Others go in Translations.', max_length=5)),
                ('ref', models.SlugField(blank=True, help_text='Short handle used by the body: [[kind:ref]]. Generated if left blank.', max_length=40)),
                ('title', models.CharField(blank=True, help_text='Heading above the table.', max_length=120)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('layout', models.CharField(choices=[('facts', 'Fact bar (under the title)'), ('impact', 'Impact callout'), ('table', 'Comparison table')], default='table', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetricGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Español')], max_length=5)),
                ('field', models.CharField(help_text='The field being translated.', max_length=40)),
                ('value', models.TextField(blank=True, help_text='Leave empty to fall back to the original.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['lang', 'field'],
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='asset',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='The language these fields are written in. Others go in Translations.', max_length=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='ref',
            field=models.SlugField(blank=True, help_text='Short handle used by the body: [[kind:ref]]. Generated if left blank.', max_length=40),
        ),
        migrations.AddField(
            model_name='metric',
            name='baseline',
            field=models.CharField(blank=True, help_text="The 'before' column, if the table has one.", max_length=40),
        ),
        migrations.AddField(
            model_name='metric',
            name='delta',
            field=models.CharField(blank=True, help_text="The 'change' column, if the table has one.", max_length=40),
        ),
        migrations.AddField(
            model_name='metric',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='The language these fields are written in. Others go in Translations.', max_length=5),
        ),
        migrations.AddField(
            model_name='metric',
            name='note',
            field=models.CharField(blank=True, help_text='Optional aside.', max_length=160),
        ),
        migrations.AddField(
            model_name='metric',
            name='ref',
            field=models.SlugField(blank=True, help_text='Stable handle, generated if blank.', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='The language these fields are written in. Others go in Translations.', max_length=5),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='The language these fields are written in. Others go in Translations.', max_length=5),
        ),
        migrations.AddField(
            model_name='tag',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='The language these fields are written in. Others go in Translations.', max_length=5),
        ),
        migrations.AlterField(
            model_name='metric',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Whose library this belongs to. Optional.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_md',
            field=models.TextField(blank=True, help_text='The case study, in markdown. Headings become the page contents. Place media and metric tables with [[asset:ref]] / [[metrics:ref]].'),
        ),
        migrations.AddField(
            model_name='metricgroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_groups', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='metricgroupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.metricgroup'),
        ),
        migrations.AddField(
            model_name='metricgroupitem',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='portfolio.metric'),
        ),
        migrations.AddField(
            model_name='metricgroup',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='groups', through='portfolio.MetricGroupItem', to='portfolio.metric'),
        ),
        migrations.AddConstraint(
            model_name='metricgroupitem',
            constraint=models.UniqueConstraint(fields=('group', 'metric'), name='unique_metric_per_group'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['content_type', 'object_id', 'lang'], name='portfolio_t_content_187be8_idx'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'lang', 'field'), name='unique_translation_per_field'),
        ),
    ]
