# Generated by Django 5.2.17 on 2026-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_backfill_refs_and_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='order',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='placement',
        ),
        migrations.AlterField(
            model_name='metric',
            name='ref',
            field=models.SlugField(blank=True, help_text='Stable handle, generated if blank.', max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('project', 'ref'), name='unique_asset_ref_per_project'),
        ),
        migrations.AddConstraint(
            model_name='metricgroup',
            constraint=models.UniqueConstraint(fields=('project', 'ref'), name='unique_group_ref_per_project'),
        ),
    ]
