# Generated by Django 5.2.17 on 2026-09-02 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('redirect_uris', models.JSONField(default=list)),
                ('scope', models.CharField(choices=[('read', 'Read only'), ('write', 'Read and write')], default='write', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OAuth client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('code_challenge', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('read', 'Read only'), ('write', 'Read and write')], default='write', max_length=10)),
                ('resource', models.CharField(blank=True, max_length=300)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='mcp_server.mcpclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What this token is for.', max_length=120)),
                ('kind', models.CharField(choices=[('static', 'Personal token'), ('oauth', 'OAuth grant')], default='static', max_length=10)),
                ('scope', models.CharField(choices=[('read', 'Read only'), ('write', 'Read and write')], default='write', max_length=10)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('resource', models.CharField(blank=True, max_length=300)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mcp_server.mcpclient')),
                ('user', models.ForeignKey(blank=True, help_text='Whose authority the token acts with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCP token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=80)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='mcp_server.mcptoken')),
            ],
            options={
                'verbose_name': 'MCP call',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mcp_server__created_121bbc_idx'), models.Index(fields=['tool'], name='mcp_server__tool_ede736_idx')],
            },
        ),
    ]
